name: Build

on:
  release:
    types: [created]

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
        # Give the default GITHUB_TOKEN write permission to commit and push the
        # added or changed files to the repository.
        contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Bun
      shell: bash
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "$HOME/.bun/bin" >> $GITHUB_PATH

    - name: Build minified version
      run: |
        bun build --minify files-to-prompt.ts --outfile minified/ftp-${{ github.ref_name }}-min.js

    ## Skip upload for now
    # - name: Upload artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ftp-minified
    #     path: minified/ftp-${{ github.ref_name }}-min.js

    - name: Commit and push minified version
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions Bot"
        git checkout main
        git add minified/ftp-${{ github.ref_name }}-min.js
        git commit -m "build: ftp-${{ github.ref_name }}-min.js"
        git push
